---
abstract: 'fisheye filter for Imager'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
  Imager: 0.65
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Imager-Filter-FishEye
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Imager: 0.65
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/p5-imager-filter-fisheye.git
version: 0.04
