---
abstract: 'fisheye filter for Imager'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0
  YAML: 0
configure_requires:
  Imager: 0.55
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Imager-Filter-FishEye
no_index:
  directory:
    - inc
    - t
requires:
  Imager: 0.55
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
